system:
  num_client: 1
  num_local_class: 10
  dataset: "CIFAR10"
  model: "ResNet18_n"
  i_seed: 235235
  num_round: 50
  res_root: "results"

client:
  fed_algo: "FedAvg"
  lr: 0.01
  batch_size: 64
  num_local_epoch: 3
  momentum: 0.9
  num_worker: 2